addSbtPlugin("org.scala-js"         % "sbt-scalajs"  % "1.14.0")
addSbtPlugin("io.indigoengine"     %% "sbt-indigo"   % "0.15.2")
addSbtPlugin("org.typelevel"        % "sbt-tpolecat" % "0.5.0")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("ch.epfl.scala"        % "sbt-scalafix" % "0.11.1")
addSbtPlugin("com.github.reibitto"  % "sbt-welcome"  % "0.4.0")
