addSbtPlugin("org.scala-js"         % "sbt-scalajs"  % "$scala_js_version$")
addSbtPlugin("io.indigoengine"     %% "sbt-indigo"   % "$indigo_version$")
addSbtPlugin("org.typelevel"        % "sbt-tpolecat" % "$sbt_tpolecat_version$")
addSbtPlugin("ch.epfl.scala"        % "sbt-scalafix" % "$scalafix_version$")
addSbtPlugin("com.github.reibitto"  % "sbt-welcome"  % "$sbt_welcome_version$")
